name: SAST Workflow

on:
  workflow_call: 

jobs:
  static-analysis-scan:
    #container:
    #  image: "docker.io/blackducksoftware/sca-tools:1.0"
    runs-on: ["sast"]
    steps:
      - uses: actions/checkout@v4
      - name: SAST Scan
        run: |
          echo "Successfully ran SAST scan"
      - name: Publish Results
        run: |
          echo "SAST scan results"
